# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DhawaAlkhreej' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DhawaAlkhreej
  
  # Helpers and extensions
  pod 'Helper4Swift' , '~> 0.1.8' # By Abdullah Alhaider https://cocoapods.org/pods/Helper4Swift

  # Formating and styling the code
  pod 'SwiftLint' , '~> 0.27.0'
  
  # Keyboard manager, https://github.com/hackiftekhar/IQKeyboardManager
  pod 'IQKeyboardManagerSwift' , '~> 6.2.1'

end
