# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DhawaAlkhreej' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DhawaAlkhreej

  # Formating and styling the code
  pod 'SwiftLint' , '~> 0.27.0'

end
